### ISSUE TITLE
canIndexInAlgolia being ignored when used on extension

### ISSUE THREAD

**Issue by jesscostello** [wilr/silverstripe-algolia#46]
I'm trying to implement some logic inside the `canIndexInAlgolia()` function to allow indexing of some objects and not others but the function doesn't seem to be getting accessed at all. 

I have extended `SilverStripe\Assets\Shortcodes\FileLink` with the `AlgoliaObjectExtension` and my intentions are to index document files that have been linked to in content blocks, hence the use of the FileLink class. I need to add a check that allows the File to be indexed only if it is a document and exclude images etc which also are FileLinks, something along the lines of this

```
    public function canIndexInAlgolia(): bool
    {
        return ($this->owner->Linked()->appCategory() == 'document') ? true : false;
    }
```
I can't seem to get this function to work within my FileLinkExtension class even just returning false without any logic and have been unable to work out if this is a bug or an issue with my setup

**Comment by wilr** [comment]
@jesscostello this should work fine (make sure you've cleared all your caches etc). Your best bet for support is the Silverstripe slack channel. DM me if you want support in there. Github issues is used for tracking known bugs rather than support requests but I can do my best.

If you put a `die();` in `canIndexInAlgolia` does your script end? If not, then you need to determine why `canIndexInAlgolia` is not being called.

`canIndexInAlgolia` is called when reindexing items so it's possible your item isn't being picked up by `AlgoliaReindex` at all. You'll need to step through that - have a look at the `AlgoliaReindex` and make sure your `FileLink` objects are even being picked up in `indexItems()`
